#Requires -Version 7.0
<#
  Copies the LIVE rice back into this repo -- the reverse of install.ps1.

  install.ps1 only ever goes repo -> live, so the repo drifts silently every time
  a config is edited in place. Nothing detected that; it stayed in sync by
  remembering to copy files by hand.

    pwsh -File .\sync.ps1            # pull live -> repo
    pwsh -File .\sync.ps1 -Check     # report differences, change nothing,
                                     # exit 1 if any (usable as a pre-commit hook)
#>
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$home_ = $env:USERPROFILE

# repo-relative path  ->  live path. The single source of truth for both
# directions; install.ps1's deploy list mirrors it.
$Map = [ordered]@{
    'wezterm\.wezterm.lua'                       = "$home_\.wezterm.lua"
    # These two were in the repo but not in this map, so every edit to the live
    # rice.json drifted away from the committed copy without anything noticing.
    'config\rice.json'                           = "$home_\.config\rice.json"
    'config\rice.schema.json'                    = "$home_\.config\rice.schema.json"
    'config\glazewm\config.yaml'                 = "$home_\.glzr\glazewm\config.yaml"
    'config\fastfetch\config.jsonc'              = "$home_\.config\fastfetch\config.jsonc"
    'config\fastfetch\duck.txt'                  = "$home_\.config\fastfetch\duck.txt"
    'powershell\Microsoft.PowerShell_profile.ps1' = "$home_\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
    'nushell\config.nu'                          = "$home_\AppData\Roaming\nushell\config.nu"
    'altsnap\AltSnap.ini'                        = "$home_\scoop\persist\altsnap\AltSnap.ini"
}
foreach ($f in 'glazewm-dwindle.ps1', 'glazewm-animcheck.ps1', 'wezterm-hotkey.ahk',
               'shadowplay-record.ps1', 'shadowplay-record.vbs', 'shadowplay-wgc-save.ps1',
               'shadowplay-wgc.vbs', 'rice-supervisor.ps1', 'rice-supervisor.vbs',
               'rice-autostart.ps1', 'rice-autostart.vbs') {
    $Map["scripts\$f"] = "$home_\.config\$f"
}
foreach ($f in Get-ChildItem "$home_\.config\lib\*.ps1" -EA SilentlyContinue) {
    $Map["scripts\lib\$($f.Name)"] = $f.FullName
}
# The one exception to the $home_ convention: Firefox reads AutoConfig from its
# application directory, next to firefox.exe, so the notification override can
# only live in Program Files. Absolute paths on purpose. Pulling live -> repo is
# a plain read and needs no elevation; pushing back does, which is why only
# install.ps1's admin step writes them.
#
# They are tracked unconditionally, so -Check reports MISSING LIVE when they are
# not there. That is the point: a Firefox update rewrites its own install
# directory and can take config.js with it, which would silently give the stock
# Windows toasts back. This is the only thing that notices.
# Vesktop notification override: the staged fragments only. The files they are
# appended to live in Vesktop's data directory and are 700 KB of vendored Vencord
# bundle -- tracking those would be tracking someone else's build output. Whether
# the append is still *in* them is checked further down instead.
foreach ($f in 'apply.ps1', 'notify-main.js', 'notify-preload.js', 'notify-renderer.js') {
    $Map["vesktop\$f"] = "$home_\.config\vesktop\$f"
}
# notifyd's sparse package: the manifest and the build script only. The .msix,
# the .cer and the stage\ tree next to them live are build output and a private
# key's public half -- generated by build.ps1 on every machine, never tracked.
foreach ($f in 'AppxManifest.xml', 'build.ps1') {
    $Map["notifyd-package\$f"] = "$home_\.config\notifyd-package\$f"
}

foreach ($ff in "$env:ProgramFiles\Firefox Developer Edition", "$env:ProgramFiles\Mozilla Firefox") {
    if (-not (Test-Path $ff)) { continue }
    $Map['firefox\config.js'] = "$ff\config.js"
    $Map['firefox\defaults\pref\config-prefs.js'] = "$ff\defaults\pref\config-prefs.js"
    break   # first install wins; two Firefox channels would map to the same repo file
}

# Rust sources: whole trees, minus build output.
$Trees = @{ 'crates' = "$home_\dev\crates" }
$Loose = @{ 'Cargo.toml' = "$home_\dev\Cargo.toml"; 'Cargo.lock' = "$home_\dev\Cargo.lock" }

$diff = @()
$copied = 0

function Sync-One($rel, $live) {
    $dst = Join-Path $repo $rel
    if (-not (Test-Path $live)) { $script:diff += "MISSING LIVE  $rel"; return }
    $same = (Test-Path $dst) -and -not (Compare-Object (Get-Content $live -Raw -EA SilentlyContinue) (Get-Content $dst -Raw -EA SilentlyContinue))
    if ($same) { return }
    $script:diff += "DIFFERS       $rel"
    if (-not $Check) {
        $dir = Split-Path $dst
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
        Copy-Item $live $dst -Force
        $script:copied++
    }
}

foreach ($k in $Map.Keys) { Sync-One $k $Map[$k] }
foreach ($k in $Loose.Keys) { Sync-One $k $Loose[$k] }

foreach ($rel in $Trees.Keys) {
    $live = $Trees[$rel]
    if (-not (Test-Path $live)) { continue }
    foreach ($f in Get-ChildItem $live -Recurse -File | Where-Object { $_.FullName -notmatch '\\target\\' }) {
        $sub = $f.FullName.Substring($live.Length).TrimStart('\')
        Sync-One (Join-Path $rel $sub) $f.FullName
    }
}

# Same idea as the Firefox pair above, one level further out. The three Vencord
# files vesktop\apply.ps1 appends to are rewritten wholesale by every Vencord
# update, which silently gives the stock blue Windows toasts back. notify-main.js
# re-applies itself when it sees that happen; this is what notices when it did
# not. Shelled out rather than reimplemented so the data-directory lookup lives in
# one place; -Check there stages nothing and writes nothing.
if (Test-Path "$repo\vesktop\apply.ps1") {
    & "$repo\vesktop\apply.ps1" -Check 6>$null | Out-Null
    if ($LASTEXITCODE -ne 0) { $diff += 'PATCH GONE    vesktop  (re-run vesktop\apply.ps1)' }
}

if ($Check) {
    if ($diff.Count) {
        Write-Host "repo is OUT OF SYNC with live ($($diff.Count)):" -ForegroundColor Yellow
        $diff | ForEach-Object { Write-Host "  $_" }
        exit 1
    }
    Write-Host 'repo matches live' -ForegroundColor Green
    exit 0
}

if ($copied) {
    Write-Host "pulled $copied file(s) from live:" -ForegroundColor Cyan
    $diff | ForEach-Object { Write-Host "  $_" }
} elseif ($diff.Count) {
    # Nothing to pull, but something is missing or unpatched live -- saying
    # 'already in sync' here would be a lie.
    Write-Host "nothing to pull, but live has gaps ($($diff.Count)):" -ForegroundColor Yellow
    $diff | ForEach-Object { Write-Host "  $_" }
} else {
    Write-Host 'already in sync' -ForegroundColor Green
}
