#Requires -Version 7.0
<#
  Copies the LIVE rice back into this repo -- the reverse of install.ps1.

  install.ps1 only ever goes repo -> live, so the repo drifts silently every time
  a config is edited in place. Nothing detected that; it stayed in sync by
  remembering to copy files by hand.

    pwsh -File .\sync.ps1            # pull live -> repo
    pwsh -File .\sync.ps1 -Check     # report differences, change nothing,
                                     # exit 1 if any (usable as a pre-commit hook)
#>
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
$home_ = $env:USERPROFILE

# repo-relative path  ->  live path. The single source of truth for both
# directions; install.ps1's deploy list mirrors it.
$Map = [ordered]@{
    'wezterm\.wezterm.lua'                       = "$home_\.wezterm.lua"
    # These two were in the repo but not in this map, so every edit to the live
    # rice.json drifted away from the committed copy without anything noticing.
    'config\rice.json'                           = "$home_\.config\rice.json"
    'config\rice.schema.json'                    = "$home_\.config\rice.schema.json"
    'config\glazewm\config.yaml'                 = "$home_\.glzr\glazewm\config.yaml"
    'config\fastfetch\config.jsonc'              = "$home_\.config\fastfetch\config.jsonc"
    'config\fastfetch\duck.txt'                  = "$home_\.config\fastfetch\duck.txt"
    'powershell\Microsoft.PowerShell_profile.ps1' = "$home_\Documents\PowerShell\Microsoft.PowerShell_profile.ps1"
    'nushell\config.nu'                          = "$home_\AppData\Roaming\nushell\config.nu"
    'altsnap\AltSnap.ini'                        = "$home_\scoop\persist\altsnap\AltSnap.ini"
}
# EVERY .ps1/.vbs/.ahk committed under scripts\ belongs here, not just the ones
# something else launches. A script left out of this list is worse than untracked:
# it is in the repo, so it looks versioned, while -Check keeps answering 'repo
# matches live' however far the live copy has moved. The one-shot tuning scripts
# (accent, boot-report, notif-banners, retire-replaced, tame-startup, trim-run)
# are exactly the ones that get edited live and never copied back, because nobody
# runs them twice in the same week.
foreach ($f in 'glazewm-dwindle.ps1', 'glazewm-animcheck.ps1', 'wezterm-hotkey.ahk',
               'shadowplay-record.ps1', 'shadowplay-record.vbs', 'shadowplay-wgc-save.ps1', 'shadowplay-verificar.ps1',
               'shadowplay-wgc.vbs', 'rice-supervisor.ps1', 'rice-supervisor.vbs',
               'rice-autostart.ps1', 'rice-autostart.vbs', 'rice-tray-promote.ps1',
               'rice-trim-background.ps1', 'rice-uninstall.ps1', 'rice-llm.ps1',
               'rice-accent.ps1', 'rice-boot-report.ps1', 'rice-notif-banners.ps1',
               'rice-retire-replaced.ps1', 'rice-tame-startup.ps1', 'rice-trim-run.ps1',
               'rice-clip-share.ps1', 'rice-onedrive-purge.ps1', 'rice-deshacer.ps1', 'rice-teclado.ps1',
               'rice-modo-juego.ps1', 'rice-usb-fix.ps1',
               'rice-audio-restaurar.ps1', 'rice-audio-restaurar-tarea.ps1') {
    $Map["scripts\$f"] = "$home_\.config\$f"
}
foreach ($f in Get-ChildItem "$home_\.config\lib\*.ps1" -EA SilentlyContinue) {
    $Map["scripts\lib\$($f.Name)"] = $f.FullName
}
# notifyd's sparse package: the manifest and the build script only. The .msix,
# the .cer and the stage\ tree next to them live are build output and a private
# key's public half -- generated by build.ps1 on every machine, never tracked.
foreach ($f in 'AppxManifest.xml', 'build.ps1') {
    $Map["notifyd-package\$f"] = "$home_\.config\notifyd-package\$f"
}

# The memory tuning lives in the PROFILE, whose directory name is random per
# machine, so it is looked up rather than hardcoded. user.js is the right file
# for this: Firefox reads it at every start and stamps prefs.js from it, so
# deleting it reverts everything on the next launch.
$ffProfile = Get-ChildItem "$home_\AppData\Roaming\Mozilla\Firefox\Profiles" -Directory -EA SilentlyContinue |
             Where-Object { $_.Name -match '\.(dev-edition-default|default-release|default)$' } |
             Sort-Object LastWriteTime -Descending | Select-Object -First 1
if ($ffProfile) { $Map['firefox\user.js'] = Join-Path $ffProfile.FullName 'user.js' }

# The one exception to the $home_ convention: Firefox reads AutoConfig from its
# application directory, next to firefox.exe, so the notification override can
# only live in Program Files. Absolute paths on purpose. Pulling live -> repo is
# a plain read and needs no elevation; pushing back does, which is why only
# install.ps1's admin step writes them.
#
# Once a Firefox install is found the pair is mapped without checking that the
# files themselves are there, so -Check reports MISSING LIVE when they are not.
# That is the point: a Firefox update rewrites its own install directory and can
# take config.js with it, which would silently give the stock Windows toasts
# back. This is the only thing that notices.
foreach ($ff in "$env:ProgramFiles\Firefox Developer Edition", "$env:ProgramFiles\Mozilla Firefox") {
    if (-not (Test-Path $ff)) { continue }
    $Map['firefox\config.js'] = "$ff\config.js"
    $Map['firefox\defaults\pref\config-prefs.js'] = "$ff\defaults\pref\config-prefs.js"
    break   # first install wins; two Firefox channels would map to the same repo file
}

# Los presets del modelo local. Viven en I: junto al modelo (17 GB no caben en
# el repo), pero el INI si merece seguimiento: es donde estan medidos el reparto
# GPU/CPU y los contextos que funcionan en este equipo.
#
# Ruta absoluta CON barra: 'I:\ai\presets.ini'. Sin ella ('I:ai\...') seria una
# ruta relativa al directorio actual DE ESA UNIDAD, y la secuencia barra+a es
# peor todavia: aqui se colo una vez como un BEL (0x07) literal dentro del
# archivo, invisible al abrirlo. Las dos formas fallan en silencio, porque la
# linea entera vive dentro de un Test-Path: el mapa se queda sin la entrada y
# -Check sigue contestando que el repo cuadra con lo vivo, con el INI sin
# versionar.
if (Test-Path 'I:\ai\presets.ini') { $Map['ai\presets.ini'] = 'I:\ai\presets.ini' }

# Rust sources: whole trees, minus build output.
$Trees = @{ 'crates' = "$home_\dev\crates" }
$Loose = @{ 'Cargo.toml' = "$home_\dev\Cargo.toml"; 'Cargo.lock' = "$home_\dev\Cargo.lock" }

$diff = @()
$copied = 0

function Sync-One($rel, $live) {
    $dst = Join-Path $repo $rel
    if (-not (Test-Path $live)) { $script:diff += "MISSING LIVE  $rel"; return }
    $same = (Test-Path $dst) -and -not (Compare-Object (Get-Content $live -Raw -EA SilentlyContinue) (Get-Content $dst -Raw -EA SilentlyContinue))
    if ($same) { return }
    $script:diff += "DIFFERS       $rel"
    if (-not $Check) {
        $dir = Split-Path $dst
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force $dir | Out-Null }
        Copy-Item $live $dst -Force
        $script:copied++
    }
}

foreach ($k in $Map.Keys) { Sync-One $k $Map[$k] }
foreach ($k in $Loose.Keys) { Sync-One $k $Loose[$k] }

foreach ($rel in $Trees.Keys) {
    $live = $Trees[$rel]
    if (-not (Test-Path $live)) { continue }
    foreach ($f in Get-ChildItem $live -Recurse -File | Where-Object { $_.FullName -notmatch '\\target\\' }) {
        $sub = $f.FullName.Substring($live.Length).TrimStart('\')
        Sync-One (Join-Path $rel $sub) $f.FullName
    }
}

# A guard that shells out to another script and reads $LASTEXITCODE only reports
# what that script chose to fail on. vesktop\apply.ps1 -Check used to be wired in
# here to catch a Vencord update wiping the notification patch, but it exits 0 --
# success -- when there is no Vesktop data directory to inspect, which is also
# what an uninstalled Vesktop looks like. So the moment the app went away the
# check went permanently green while still appearing to guard something. If a
# check like this is ever added back, the "cannot tell" case has to be a distinct
# exit code from "checked and fine", or it is not a check.
#
# Nothing replaces it: notifyd draws every app's notifications from the system
# listener, so there is no per-app patch left to go missing.

# Un .ps1 que vive en .config y no esta en $Map es justo el caso que el
# comentario de arriba describe como "peor que no versionado": -Check
# contestaria 'repo matches live' mientras el archivo no esta en ningun lado.
# Paso de verdad con rice-modo-juego.ps1 y rice-usb-fix.ps1, 210 lineas entre
# los dos. Detectarlo es barato; acordarse, no.
$enMapa = $Map.Values | ForEach-Object { Split-Path $_ -Leaf }
$huerfanos = @(Get-ChildItem "$home_.config*.ps1" -EA SilentlyContinue |
    Where-Object { $enMapa -notcontains $_.Name } |
    ForEach-Object { $_.Name })
if ($huerfanos.Count) {
    Write-Host "scripts vivos que NO estan en el mapa de sync ($($huerfanos.Count)):" -ForegroundColor Yellow
    $huerfanos | ForEach-Object { Write-Host "  .config$_" }
    Write-Host "  -> agregalos a la lista de arriba o no se versionan nunca"
}

if ($Check) {
    if ($diff.Count) {
        Write-Host "repo is OUT OF SYNC with live ($($diff.Count)):" -ForegroundColor Yellow
        $diff | ForEach-Object { Write-Host "  $_" }
    }
    # Los huerfanos ya se listaron arriba; aqui solo deciden el codigo de
    # salida, para que un CI o un hook los trate como el problema que son.
    if ($diff.Count -or $huerfanos.Count) { exit 1 }
    Write-Host 'repo matches live' -ForegroundColor Green
    exit 0
}

if ($copied) {
    Write-Host "pulled $copied file(s) from live:" -ForegroundColor Cyan
    $diff | ForEach-Object { Write-Host "  $_" }
} elseif ($diff.Count) {
    # Nothing to pull, but something is missing or unpatched live -- saying
    # 'already in sync' here would be a lie.
    Write-Host "nothing to pull, but live has gaps ($($diff.Count)):" -ForegroundColor Yellow
    $diff | ForEach-Object { Write-Host "  $_" }
} else {
    Write-Host 'already in sync' -ForegroundColor Green
}
